apiVersion: apps/v1
kind: Deployment
metadata:
  name: TriangleEarthSociety
spec:
  replicas: 3
  selector:
    matchLabels:
      app: TriangleEarthSociety
  template:
    metadata:
      labels:
        app: TriangleEarthSociety
        version: v0.15
    spec:
      containers:
      - name: TriangleEarthSociety
        image: toolboc/TriangleEarthSociety
        ports:
        - containerPort: 35222
          name: TriangleEarthSociety
          protocol: TCP